# Generated by Django 4.0.4 on 2022-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='color',
            field=models.CharField(choices=[('beige', 'Beige'), ('purple', 'Purple'), ('red', 'Red')], max_length=20, null='True', verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=10, null='True', verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=10, verbose_name='만족도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakaoId',
            field=models.CharField(max_length=50, verbose_name='카카오톡 ID'),
        ),
    ]
