# Generated by Django 4.0.4 on 2022-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('beige', 'Beige'), ('purple', 'Purple')], max_length=20, null='True', verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=10, null='True', verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=10, verbose_name='만족도'),
        ),
    ]
