# Generated by Django 4.0.4 on 2022-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_apply_color_alter_apply_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterField(
            model_name='apply',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('beige', 'Beige'), ('red', 'Red')], max_length=20, null='True', verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10, null='True', verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('1', '1'), ('2', '2'), ('4', '4')], max_length=10, verbose_name='만족도'),
        ),
    ]
