# Generated by Django 4.0.4 on 2022-05-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_alter_apply_color_alter_apply_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('beige', 'Beige')], max_length=20, null='True', verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='size',
            field=models.CharField(choices=[('M', 'Medium'), ('S', 'Small'), ('L', 'Large')], max_length=10, null='True', verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('3', '3'), ('1', '1')], max_length=10, verbose_name='만족도'),
        ),
    ]
